import { expect, test } from "@playwright/test"
import { Buffer } from "node:buffer"

async function openNewTask(page) {
  await page.goto("/")
  await page.getByRole("button", { name: "New task" }).click()
  await expect(page.getByRole("heading", { name: "New Task" })).toBeVisible()
}

test("validates each wizard step and preserves inputs when moving back", async ({ page }) => {
  await openNewTask(page)
  await page.getByRole("button", { name: "Start custom task" }).click()
  await expect(page.getByText("Step 1 of 3")).toBeVisible()
  await page.getByLabel("Task title").fill("Review policy controls")
  await page.getByRole("button", { name: "Continue" }).click()
  await expect(page.getByRole("alert")).toContainText("Work brief is required")
  await page.getByLabel("Work brief").fill("Review the current policy controls and identify gaps.")
  await page.getByLabel("Expected output").fill("Control review memo")
  await page.getByRole("button", { name: "Continue" }).click()
  await expect(page.getByText("Step 2 of 3")).toBeVisible()
  await page.getByLabel("Sensitivity").selectOption("high")
  await page.getByRole("button", { name: "Continue" }).click()
  await expect(page.getByText("Step 3 of 3")).toBeVisible()
  await expect(page.getByText("Review policy controls")).toBeVisible()
  await expect(page.getByText("Control review memo")).toBeVisible()
  await page.getByRole("button", { name: "Back" }).click()
  await expect(page.getByLabel("Sensitivity")).toHaveValue("high")
  await page.getByRole("button", { name: "Back" }).click()
  await expect(page.getByLabel("Task title")).toHaveValue("Review policy controls")
  await expect(page.getByLabel("Work brief")).toHaveValue("Review the current policy controls and identify gaps.")
})

test("saves and restores a custom task draft", async ({ page }) => {
  await openNewTask(page)
  await page.getByRole("button", { name: "Start custom task" }).click()
  await page.getByLabel("Task title").fill("Saved intake draft")
  await page.getByLabel("Work brief").fill("Keep this draft available after leaving the page.")
  await page.getByRole("button", { name: "Save draft" }).click()
  await expect(page.getByRole("status")).toContainText("Draft saved")
  await page.getByRole("button", { name: "Dashboard" }).click()
  await page.getByRole("button", { name: "New task" }).click()
  await expect(page.getByLabel("Task title")).toHaveValue("Saved intake draft")
  await expect(page.getByLabel("Work brief")).toHaveValue("Keep this draft available after leaving the page.")
})

test("accepts txt and md, removes files, and rejects pdf without clearing fields", async ({ page }) => {
  await openNewTask(page)
  await page.getByRole("button", { name: "Start custom task" }).click()
  await page.getByLabel("Task title").fill("Review policy controls")
  await page.getByLabel("Work brief").fill("Review the current policy controls and identify gaps.")
  await page.getByRole("button", { name: "Continue" }).click()
  await page.getByLabel("Supporting files").setInputFiles({ name: "context.md", mimeType: "text/markdown", buffer: Buffer.from("# Context") })
  await expect(page.getByText("context.md")).toBeVisible()
  await expect(page.getByText("9 B")).toBeVisible()
  await expect(page.getByText("Ready")).toBeVisible()
  await page.getByLabel("Supporting files").setInputFiles({ name: "brief.pdf", mimeType: "application/pdf", buffer: Buffer.from("not a pdf") })
  await expect(page.getByRole("alert")).toContainText("Only .txt and .md")
  await expect(page.getByRole("alert")).toContainText("planned later")
  await page.getByRole("button", { name: "Back" }).click()
  await expect(page.getByLabel("Task title")).toHaveValue("Review policy controls")
  await page.getByRole("button", { name: "Continue" }).click()
  await page.getByRole("button", { name: "Remove context.md" }).click()
  await expect(page.getByText("context.md")).toHaveCount(0)
})

test("reviews and analyzes a custom task through the existing contract", async ({ page }) => {
  await openNewTask(page)
  await page.getByRole("button", { name: "Start custom task" }).click()
  await page.getByLabel("Task title").fill("Summarize research notes")
  await page.getByLabel("Work brief").fill("Summarize internal research notes for the product team.")
  await page.getByLabel("Expected output").fill("One-page summary")
  await page.getByRole("button", { name: "Continue" }).click()
  await page.getByLabel("Audience").selectOption("internal")
  await page.getByLabel("Sensitivity").selectOption("low")
  await page.getByLabel("Urgency").selectOption("medium")
  await page.getByLabel("Budget range").selectOption("low")
  await page.getByRole("button", { name: "Continue" }).click()
  await expect(page.getByRole("heading", { name: "Review task" })).toBeVisible()
  await page.getByRole("button", { name: "Analyze task" }).click()
  await expect(page.getByRole("heading", { name: "Recommendation Result", exact: true })).toBeVisible()
})
