import { TextDecoder } from "node:util"
import { classifySensitivity } from "../server/agentPolicy.js"
import { ApiError,getConfig,getServiceClient,hashBody,readBody,requireAdmin,requireMethod,rpc,sendJson,withApi } from "./_lib.js"
const allowedExtensions=new Set([".txt",".md"])
function extension(name){const lower=String(name||"").toLowerCase();return lower.endsWith(".md")?".md":lower.endsWith(".txt")?".txt":""}
function decodeText(buffer){if(buffer.includes(0))throw new ApiError(400,"Attachment contains binary data.","invalid_attachment");try{const text=new TextDecoder("utf-8",{fatal:true}).decode(buffer);if([...text].some((character)=>{const code=character.charCodeAt(0);return code<32&&code!==9&&code!==10&&code!==13}))throw new ApiError(400,"Attachment contains binary control characters.","invalid_attachment");return text}catch(error){if(error instanceof ApiError)throw error;throw new ApiError(400,"Attachment is not valid UTF-8 text.","invalid_attachment")}}
export default withApi(async(req,res,traceId)=>{requireMethod(req,"POST");const user=await requireAdmin(req);const body=await readBody(req);const supabase=getServiceClient();const config=getConfig();if(!body.taskId||!["sign","confirm"].includes(body.action))throw new ApiError(400,"taskId and attachment action are required.","invalid_attachment");const{data:task}=await supabase.from("tasks").select("id,sensitivity,workflow_status").eq("id",body.taskId).eq("owner_user_id",user.id).maybeSingle();if(!task)throw new ApiError(404,"Task not found.","task_not_found");
 if(body.action==="sign"){const ext=extension(body.fileName);if(!allowedExtensions.has(ext)||!Number.isInteger(body.byteSize)||body.byteSize<1||body.byteSize>config.attachmentMaxBytes)throw new ApiError(400,"Only .txt and .md files within the configured size limit are accepted.","invalid_attachment");const safe=body.fileName.replace(/[^A-Za-z0-9._-]/g,"_");const path=`${user.id}/${task.id}/${crypto.randomUUID()}-${safe}`;const{data,error}=await supabase.storage.from("task-attachments").createSignedUploadUrl(path);if(error)throw error;return sendJson(res,201,{ok:true,upload:{path,token:data.token,signedUrl:data.signedUrl}},traceId)}
 let confirmed=false;const ext=extension(body.fileName);if(!allowedExtensions.has(ext)||!body.storagePath?.startsWith(`${user.id}/${task.id}/`))throw new ApiError(400,"Attachment metadata is invalid.","invalid_attachment");const remove=async()=>{const{error}=await supabase.storage.from("task-attachments").remove([body.storagePath]);if(error)throw new ApiError(502,"Rejected upload cleanup failed.","storage_cleanup_failed")};try{const{data:blob,error}=await supabase.storage.from("task-attachments").download(body.storagePath);if(error)throw error;if(blob.size<1||blob.size>config.attachmentMaxBytes)throw new ApiError(400,"Attachment size is invalid.","invalid_attachment");const text=decodeText(Buffer.from(await blob.arrayBuffer()));if(text.length>config.attachmentMaxCharacters)throw new ApiError(409,"Attachment exceeds the character limit.","attachment_limit");const mime=ext===".md"?"text/markdown":"text/plain";const sensitivity=classifySensitivity({declaredSensitivity:task.sensitivity,text});const key=`confirm:${body.storagePath}`;const result=await rpc(supabase,"phase22_confirm_attachment",{p_owner_user_id:user.id,p_task_id:task.id,p_idempotency_key:key,p_request_hash:hashBody({taskId:task.id,path:body.storagePath,size:blob.size,mime}),p_file_name:body.fileName,p_storage_path:body.storagePath,p_mime_type:mime,p_byte_size:blob.size,p_extracted_text:text,p_sensitivity_status:sensitivity.status,p_trace_id:traceId});if(result.state==="in_progress")return sendJson(res,202,{ok:false,status:"in_progress"},traceId);confirmed=true;const id=result.resource_id||result.response_body?.attachment_id;const{data:attachment,error:readError}=await supabase.from("task_attachments").select("id,task_id,file_name,mime_type,byte_size,extracted_character_count,sensitivity_status,created_at").eq("id",id).single();if(readError)throw readError;return sendJson(res,201,{ok:true,attachment,sensitivity},traceId)}catch(error){if(!confirmed)await remove();throw error}})
