import { ApiError, getServiceClient, hashBody, readBody, requireAdmin, requireIdempotencyKey, rpc, sendJson, withApi } from "./_lib.js"
function newTaskId() { return `task_${crypto.randomUUID()}` }
function payload(body) { const required=["title","description","expectedOutput","audience","sensitivity","urgency","budgetRange"]; for(const field of required) if(!String(body[field]||"").trim()) throw new ApiError(400,`${field} is required.`,"invalid_task"); return { title:body.title.trim(),description:body.description.trim(),expected_output:body.expectedOutput.trim(),deadline:body.deadline||"",audience:body.audience,sensitivity:body.sensitivity,urgency:body.urgency,budget_range:body.budgetRange } }
const safeSelect="id,owner_user_id,title,description,expected_output,deadline,audience,sensitivity,urgency,budget_range,workflow_status,source,version,archived_at,selected_execution_option_id,selected_execution_option_snapshot,created_at,updated_at,task_attachments(id,file_name,mime_type,byte_size,extracted_character_count,sensitivity_status,created_at),executions(*)"
export default withApi(async(req,res,traceId)=>{const user=await requireAdmin(req);const supabase=getServiceClient();
 if(req.method==="GET"){const{data,error}=await supabase.from("tasks").select(safeSelect).eq("owner_user_id",user.id).order("created_at",{ascending:false});if(error)throw error;return sendJson(res,200,{ok:true,tasks:data},traceId)}
 if(req.method==="POST"){const body=await readBody(req);const key=requireIdempotencyKey(req);const id=newTaskId();const result=await rpc(supabase,"phase22_create_task",{p_owner_user_id:user.id,p_idempotency_key:key,p_request_hash:hashBody(body),p_task_id:id,p_payload:payload(body),p_trace_id:traceId});if(result.state==="in_progress")return sendJson(res,202,{ok:false,status:"in_progress"},traceId);const taskId=result.resource_id||result.response_body?.task_id||id;const{data,error}=await supabase.from("tasks").select(safeSelect).eq("id",taskId).eq("owner_user_id",user.id).single();if(error)throw error;return sendJson(res,201,{ok:true,task:data},traceId)}
 if(req.method==="PATCH"){const body=await readBody(req);if(!body.taskId||!Number.isInteger(body.version))throw new ApiError(400,"taskId and version are required.","invalid_task_update");await rpc(supabase,"phase22_update_task_content",{p_owner_user_id:user.id,p_task_id:body.taskId,p_expected_version:body.version,p_payload:payload(body),p_trace_id:traceId});const{data,error}=await supabase.from("tasks").select(safeSelect).eq("id",body.taskId).eq("owner_user_id",user.id).single();if(error)throw error;return sendJson(res,200,{ok:true,task:data},traceId)}
 if(req.method==="DELETE"){const body=await readBody(req);const key=requireIdempotencyKey(req);if(!body.taskId)throw new ApiError(400,"taskId is required.","invalid_delete");if(body.hardDelete!==true){const result=await rpc(supabase,"phase22_archive_task",{p_owner_user_id:user.id,p_task_id:body.taskId,p_idempotency_key:key,p_request_hash:hashBody(body),p_trace_id:traceId});if(result.state==="in_progress")return sendJson(res,202,{ok:false,status:"in_progress"},traceId);const{data,error}=await supabase.from("tasks").select(safeSelect).eq("id",body.taskId).eq("owner_user_id",user.id).single();if(error)throw error;return sendJson(res,200,{ok:true,task:data},traceId)}
  if(body.confirmation!=="DELETE")throw new ApiError(400,"Type DELETE to permanently remove an archived task.","delete_confirmation_required");const{data:task,error:lookupError}=await supabase.from("tasks").select("id,workflow_status,task_attachments(storage_path)").eq("id",body.taskId).eq("owner_user_id",user.id).maybeSingle();if(lookupError)throw lookupError;if(!task||task.workflow_status!=="archived")throw new ApiError(409,"Only an archived task can be deleted permanently.","delete_conflict");if(task.task_attachments?.length){const{error}=await supabase.storage.from("task-attachments").remove(task.task_attachments.map(item=>item.storage_path));if(error)throw new ApiError(502,"Private attachment cleanup failed. The archived task was kept for a safe retry.","storage_cleanup_failed")};await rpc(supabase,"phase22_hard_delete_task",{p_owner_user_id:user.id,p_task_id:body.taskId,p_idempotency_key:key,p_request_hash:hashBody(body),p_trace_id:traceId});return sendJson(res,200,{ok:true},traceId)}
 throw new ApiError(405,"This endpoint does not support that method.","method_not_allowed")})
