import { formatLabel } from "./formatLabel"
import { RecommendationHero } from "./RecommendationHero"
import { SectionCard } from "./SectionCard"

function ScoreBar({ label, score }) {
  return <div><div className="mb-1 flex items-center justify-between text-sm"><span className="font-medium text-slate-700">{label}</span><span className="text-slate-500">{score}</span></div><div aria-label={`${label} score`} aria-valuemax={100} aria-valuemin={0} aria-valuenow={score} className="score-track h-2 rounded-full" role="progressbar"><div className="score-fill h-2 rounded-full" style={{ width: `${score}%` }} /></div></div>
}

export function RecommendationCard({ recommendation, explanation, selectedOption }) {
  return <SectionCard><h2 className="mb-4 text-lg font-semibold text-slate-950">Recommendation result</h2><RecommendationHero recommendation={recommendation} selectedOption={selectedOption} /><div className="mt-6 grid gap-4 lg:grid-cols-3"><ScoreBar label="Human fit" score={recommendation.humanFitScore} /><ScoreBar label="Agent fit" score={recommendation.agentFitScore} /><ScoreBar label="Hybrid fit" score={recommendation.hybridFitScore} /></div><div className="mt-6 grid gap-5 lg:grid-cols-3"><div><h3 className="text-sm font-semibold uppercase text-slate-500">Why {formatLabel(recommendation.recommendedPath)}</h3><ul className="mt-3 space-y-2 text-sm text-slate-700">{explanation.topReasons.map((reason) => <li key={reason} className="info-tile px-3 py-2">{reason}</li>)}</ul></div><div><h3 className="text-sm font-semibold uppercase text-slate-500">Alternatives</h3><div className="mt-3 space-y-3">{explanation.alternatives.map((alternative) => <div key={alternative.path} className="info-tile p-3"><p className="font-medium text-slate-900">{formatLabel(alternative.path)}</p><p className="mt-1 text-sm text-slate-600">{alternative.reason}</p></div>)}</div></div><div><h3 className="text-sm font-semibold uppercase text-slate-500">Risk signals</h3><dl className="mt-3 space-y-2 text-sm text-slate-700">{Object.entries(explanation.keyFactors).map(([key, value]) => <div key={key} className="info-tile flex justify-between gap-3 px-3 py-2"><dt>{formatLabel(key)}</dt><dd className="font-medium">{formatLabel(value)}</dd></div>)}</dl></div></div><div className="mt-6"><h3 className="text-sm font-semibold uppercase text-slate-500">Route-changing conditions</h3><ul className="mt-3 grid gap-2 text-sm text-slate-700 sm:grid-cols-2">{explanation.conditions.map((condition) => <li key={condition} className="info-tile px-3 py-2">{condition}</li>)}</ul></div></SectionCard>
}
